name: Generate Test Coverage Report

on:
  push:
    paths:
      - 'src/**'
      - 'include/**'
      - 'test/**'
      - '.github/workflows/Generate Coverage.yml'
      - 'platformio.ini'

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Install Coverage Tools
        run: sudo apt-get install -y lcov

      - name: Compile with Coverage
        run: platformio test --environment native

      - name: Capture Coverage Data
        run: |
          # Capture la couverture pour tous les fichiers compilés
          lcov --capture --directory . --output-file coverage.info --rc branch_coverage=1 --rc function_coverage=1 --rc geninfo_unexecuted_blocks=1
          
          # Retirer les fichiers tests et PlatformIO
          lcov --remove coverage.info 'test/*' '*/.pio/*' --output-file coverage_filtered.info
          
          # Inclure tous les fichiers src et include même non exécutés
          lcov --extract coverage_filtered.info "*/include/*" "*/src/*" --output-file coverage_project.info
          
          # Lister la couverture finale
          lcov --list coverage_project.info

      - name: Generate HTML Report
        run: |
          rm -rf docs/coverage_report
          mkdir -p docs/coverage_report
          genhtml coverage_project.info --output-directory docs/coverage_report

      - name: Commit Coverage Report
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add docs/coverage_report/*
          git commit -m "Update coverage report" || echo "No changes to commit"
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
